theme: jekyll-theme-cayman
markdown: kramdown
highlighter: rouge
google_analytics: UA-2133915535-1

kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class   : 'syntax'

